name: revive

on:
  push:
    branches:
    - main
  pull_request:

env:
  GOPATH: /home/runner/go

permissions:
  contents: read

jobs:
  revive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: '1.22.5'
      - uses: actions/checkout@v4
      - uses: morphy2k/revive-action@v2
