name: test

on:
  push:
    branches:
    - main
  pull_request:

env:
  GOPATH: /home/runner/go

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: '1.22.6'
      - uses: actions/checkout@v4
      - uses: n8maninger/action-golang-test@v2
        with:
          args: "-timeout=30m"
